global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 10.10.10.2:161  # Target SNMP device (IP perangkat router)
    metrics_path: /snmp
    params:
      module: [if_mib]  # Sesuaikan modul dengan snmp.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9117  # Sesuaikan dengan port yang diekspos
