version: '3'  
services:  
  prometheus:  
    image: prom/prometheus  
    container_name: prometheus  
    volumes:  
      - "/etc/capstone/prometheus.yml:/etc/prometheus/prometheus.yml"  # Pastikan file ini ada
    ports:  
      - "9090:9090"  

  grafana:  
    image: grafana/grafana  
    container_name: grafana  
    ports:  
      - "3000:3000"  
    restart: unless-stopped  
    environment:  
      - GF_SECURITY_ADMIN_USER=admin  
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    volumes:  
      - ./grafana:/etc/grafana/provisioning/datasources  

  snmp-exporter:  
    image: prom/snmp-exporter  
    container_name: snmp-exporter  
    restart: unless-stopped  
    ports:  
      - "9116:9116"  # Sesuaikan port
    volumes:  
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml  # Pastikan jalur file ini benar


